name: Build Plugin and Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0, v0.2.1

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a current LTS version

      - name: Install dependencies
        run: npm ci # 'ci' is generally preferred for CI environments

      - name: Build plugin
        run: npm run build # This should output main.js, manifest.json

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload main.js to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.js # Adjust path if build outputs to dist/
          asset_name: main.js
          asset_content_type: application/javascript

      - name: Upload manifest.json to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./manifest.json # Adjust path if build outputs to dist/
          asset_name: manifest.json
          asset_content_type: application/json

      # Optional: Create a zip archive of the plugin files
      - name: Create ZIP archive
        run: zip auto-slugger-plugin.zip main.js manifest.json # Add styles.css if present

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./auto-slugger-plugin.zip
          asset_name: auto-slugger-plugin-${{ github.ref_name }}.zip
          asset_content_type: application/zip
